import type { Metadata } from "next";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/patterns/page-header";
import { ReportExport } from "@/components/patterns/report-export";
import { COMPANY_HEALTH, INSIGHTS, KPIS } from "@/lib/data/mock";
import { formatCurrency } from "@/lib/utils";

export const metadata: Metadata = { title: "Reports" };

export default function ReportsPage() {
  return (
    <main id="main-content" className="mx-auto max-w-4xl space-y-6 px-6 py-8">
      <PageHeader
        title="Reports"
        description="Board-ready executive briefing compiled from live agent signals. Export to share."
        actions={<ReportExport health={COMPANY_HEALTH} kpis={KPIS} insights={INSIGHTS} />}
      />

      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between gap-2">
            <CardTitle className="text-base">Executive Briefing</CardTitle>
            <Badge variant="success">Health {COMPANY_HEALTH.score}/100</Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-5">
          <p className="text-sm text-muted-foreground">{COMPANY_HEALTH.summary}</p>

          <div>
            <h2 className="mb-2 text-sm font-semibold">Key Metrics</h2>
            <ul className="grid gap-1 text-sm sm:grid-cols-2">
              {KPIS.map((k) => (
                <li key={k.id} className="flex justify-between border-b py-1">
                  <span className="text-muted-foreground">{k.label}</span>
                  <span className="tabular-nums font-medium">
                    {k.unit === "currency" ? formatCurrency(k.value) : k.unit === "percent" ? `${k.value}%` : k.value}{" "}
                    <span className={k.deltaPct >= 0 ? "text-success" : "text-destructive"}>
                      ({k.deltaPct >= 0 ? "+" : ""}
                      {k.deltaPct}%)
                    </span>
                  </span>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h2 className="mb-2 text-sm font-semibold">Top Risks &amp; Insights</h2>
            <ul className="space-y-2 text-sm">
              {INSIGHTS.map((i) => (
                <li key={i.id} className="flex items-start gap-2">
                  <Badge variant={i.severity === "high" || i.severity === "critical" ? "destructive" : "warning"}>
                    {i.severity}
                  </Badge>
                  <span>
                    <span className="font-medium">{i.title}</span> — {i.narrative}
                  </span>
                </li>
              ))}
            </ul>
          </div>

          <p className="border-t pt-3 text-xs text-muted-foreground">
            Generated by Helm. AI recommends; humans decide. All actions are approval-gated and recorded in the audit trail.
          </p>
        </CardContent>
      </Card>
    </main>
  );
}
