"use client";

import { Download, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { CompanyHealth, Insight, Kpi } from "@/lib/types";
import { formatCurrency } from "@/lib/utils";

function kpiValue(k: Kpi): string {
  if (k.unit === "currency") return formatCurrency(k.value);
  if (k.unit === "percent") return `${k.value}%`;
  return String(k.value);
}

function buildMarkdown(health: CompanyHealth, kpis: Kpi[], insights: Insight[]): string {
  const lines: string[] = [];
  lines.push(`# Executive Briefing — ${new Date().toLocaleDateString()}`);
  lines.push("");
  lines.push(`**Company Health: ${health.score}/100 (${health.label.replace("_", " ")})**`);
  lines.push("");
  lines.push(health.summary);
  lines.push("");
  lines.push("## Key Metrics");
  kpis.forEach((k) => lines.push(`- **${k.label}:** ${kpiValue(k)} (${k.deltaPct >= 0 ? "+" : ""}${k.deltaPct}%)`));
  lines.push("");
  lines.push("## Top Risks & Insights");
  insights.forEach((i) =>
    lines.push(`- [${i.severity.toUpperCase()} · ${i.confidence}%] **${i.title}** — ${i.narrative}`),
  );
  lines.push("");
  lines.push("_Generated by Helm. AI recommends; humans decide. All actions are approval-gated and audited._");
  return lines.join("\n");
}

export function ReportExport({
  health,
  kpis,
  insights,
}: {
  health: CompanyHealth;
  kpis: Kpi[];
  insights: Insight[];
}) {
  function download() {
    const md = buildMarkdown(health, kpis, insights);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `helm-executive-briefing-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="flex items-center gap-2">
      <Button variant="outline" size="sm" onClick={download}>
        <Download className="h-4 w-4" aria-hidden="true" />
        Download Markdown
      </Button>
      <Button variant="outline" size="sm" onClick={() => window.print()}>
        <Printer className="h-4 w-4" aria-hidden="true" />
        Print / PDF
      </Button>
    </div>
  );
}
